version: '3'

services:
  pyca-schedule:
    entrypoint: ["pyca", "schedule"]
    container_name: pyca-schedule
    image: lkiesow/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf
    links:
      - database
  pyca-ingest:
    entrypoint: ["pyca", "ingest"]
    container_name: pyca-ingest
    image: lkiesow/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf
    links:
      - database
  pyca-capture:
    entrypoint: ["pyca", "capture"]
    container_name: pyca-capture
    image: lkiesow/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf
    links:
      - database
  pyca-agentstate:
    entrypoint: ["pyca", "agentstate"]
    container_name: pyca-agentstate
    image: lkiesow/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf
    links:
      - database
  pyca-ui:
    entrypoint: ["gunicorn", "--config=/etc/pyca/gunicorn.conf.py", "pyca.ui:app"]
    container_name: pyca-ui
    image: lkiesow/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf
    ports:
      - 127.0.0.1:8000:8000
    links:
      - database
  database:
    container_name: pyca-postgres
    image: docker.io/library/postgres:12.3
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    #volumes:
    #  - pyca-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pyca
      - POSTGRES_USER=pyca
      - POSTGRES_DB=pyca
