version: '3'

volumes:
  pyca: {}
  database: {}

services:
  pyca-schedule:
    command: schedule
    image: ghcr.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca

  pyca-ingest:
    command: ingest
    image: ghcr.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca

  pyca-capture:
    command: capture
    image: ghcr.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca

  pyca-agentstate:
    command: agentstate
    image: ghcr.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca

  pyca-ui:
    entrypoint: ["gunicorn", "--config=/etc/pyca/gunicorn.conf.py", "pyca.ui:app"]
    image: ghcr.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca
    ports:
      - "8000:8000"

  database:
    image: docker.io/library/postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=pyca
      - POSTGRES_USER=pyca
      - POSTGRES_DB=pyca
    volumes:
      - database:/var/lib/postgresql/data
