version: '3'

volumes:
  pyca: {}

services:
  pyca-schedule:
    command: schedule
    image: quay.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.sqlite.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca

  pyca-ingest:
    command: ingest
    image: quay.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.sqlite.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca

  pyca-capture:
    command: capture
    image: quay.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.sqlite.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca

  pyca-agentstate:
    command: agentstate
    image: quay.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.sqlite.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca

  pyca-ui:
    entrypoint: ["gunicorn", "--config=/etc/pyca/gunicorn.conf.py", "pyca.ui:app"]
    image: quay.io/opencast/pyca
    restart: always
    volumes:
      - ./pyca.sqlite.conf:/etc/pyca/pyca.conf:ro
      - pyca:/var/lib/pyca
    ports:
      - "8000:8000"
